import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/container/Hero'
import Projects from '@/container/Projects'
import Stacks from '@/container/Stacks'
import ScrollContainer from '@/components/others/ScrollContainer'
import About from '@/container/About'
import Footer from '@/Layout/Footer'
import Test from '@/container/Test'
import Container from '@/container/Container'
import { Suspense, UIEvent, useEffect, useState } from 'react'
import Work from '@/container/Work'
import { useScroll, animated } from '@react-spring/web'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { scrollYProgress } = useScroll()
  
  return (
    <>
      <Head>
        <title>Ayooluwa Aduwo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
            <Hero />
            {/* <animated.div>
              <Projects />
            </animated.div> */}
          
          <animated.div>
            <Stacks />
          </animated.div>
          
          <animated.div>
            <Work />
          </animated.div>
          
          <animated.div>
            <About />
          </animated.div>
          
          <Container />
          
        </>
        
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  )
}
