import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/container/Hero'
import Projects from '@/container/Projects'
import Stacks from '@/container/Stacks'
import ScrollContainer from '@/components/others/ScrollContainer'
import About from '@/container/About'
import Footer from '@/Layout/Footer'
import Test from '@/container/Test'
import Container from '@/container/Container'
import React, { Suspense, UIEvent, useEffect, useState } from 'react'
import Work from '@/container/Work'
import { useScroll, useSpring, animated } from '@react-spring/web'

const inter = Inter({ subsets: ['latin'] })

const AllComponents = () => {
  return (
    <React.Fragment>
    <main>
        <>
          <Suspense fallback={(<div>Error Bringing Up Page</div>)}>
            <Hero />
          </Suspense>
          
          {/* <animated.div>
            <Projects />
          </animated.div> */}
      
          <Stacks />
          <Work />
          <About />        
        <Container />
        
      </>
    </main>
    <footer>
    <Footer />
  </footer>
  </React.Fragment>
  )
}

export default function Home() {
  const { scrollYProgress } = useScroll()
  const [showPage, setShowPage] = useState(false);

  const pageAnimation = useSpring({
    transform: showPage ? 'translateY(0%)' : 'translateY(100%)',
    opacity: showPage ? 1 : 0,
  });

  const handleClick = () => {
    setShowPage(true);
  };
  
  return (
    <>
      <Head>
        <title>Ayooluwa Aduwo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black h-screen'>
        <button className='bg-red-600 p-4 mt-20' onClick={handleClick}>Helklo world</button>

        <animated.div className="page" style={pageAnimation}>
          
            <AllComponents />
        </animated.div>
        
      </main>
      
    </>
  )
}
